[build]
  # this is the dir that will be published
  publish = "dist/"
  # command to setup your SSR environment
  command = "yarn generate"


[template.environment]
  BASE_URL=https://aymanemx.com
  GOOGLE_ANALYTICS_ID=
  NOTION_TABLE_ID="ceef6f1a895a46b2a0e4a87b41405547"
  NOTION_ABOUT_PAGE_ID="ad2346af0894443d8906cf78de4f310f"
  GITHUB_USERNAME=aymaneMx
  DEV_LOGO="AymaneMx"
  DEV_NAME="Aymane max"
  DEV_DESCRIPTION="a passionate Python developer from Morocco who loves to build and deliver quality products."
  DEV_ROLE="Software Engineer"
  DEV_GITHUB_LINK="https://github.com/aymaneMx"
  DEV_TWITTER_LINK="https://twitter.com/aymane_max"
  DEV_LINKEDIN_LINK="https://www.linkedin.com/in/aymane-mimouni/"
